# Общие параметры
# --- Logging (loguru) ---
logging:
  console:
    level: "WARNING"   # Уровень логов в консоль
  file:
    level: "DEBUG"  # Уровень логов в файл
    rotation: "1 MB"  # Ротация loguru: например "1 MB", "1 day", "00:00" и т.п.
    # path: "sync.log"  # Файл лога (абсолютный или относительный путь — от рабочей директории запуска)
    # retention: "7 days"  # (опционально) хранить N дней/период
    # compression: "zip"   # (опционально) сжимать архивы
