# Общие параметры
# --- Logging (loguru) ---
# Все значения параметров, кроме path и name заданы в программе.
# При желании их можно изменить здесь
# path или name задавать обязательно.

#logging:
#  console:
#    level: "WARNING"   # Уровень логов в консоль
#  file:
#    level: "DEBUG"  # Уровень логов в файл
#    rotation: "1 MB"  # Ротация loguru: например "1 MB", "1 day", "00:00" и т.п.
#    path: # Путь на файл журнализации
#    name: # Используется если path не задан
#    format: >
#        {time:YYYY-MM-DD HH:mm:ss} | {level:<8} |
#        {file.path}{function}:{line} - {message}
#    retention: "7 days"
#    compression: "zip"
