include: config.yaml
local_dir: 'C:\Дистрибутив\DESCRIPTIONS\'
# --- FTP (удалённый репозиторий) ---
ftp_root: "/pub/support/galaktika/bug_fix/GAL910/DESCRIPTIONS/"  # Корень на FTP
# Эти параметры есть в SyncConfig, но сейчас не заданы (будут взяты дефолты):
# ftp_repeat: 3                # Количество повторов при сетевой ошибке
# ftp_retry_delay_seconds: 1   # Пауза между повторами, секунды
# ftp_blocksize: 65536         # Размер блока чтения при скачивании, байты

# Если new_dir/old_dir не заданы — будут local_dir/NEW и local_dir/OLD
# Можно переопределить явно (если нужно):
# new_dir:
# old_dir:

logging:
  console:
    level: "WARNING"
  file:
    level: "INFO"  # Уровень логов в файл
    name: "sync.log"

excel:
  excel_path: 'c:\\Дистрибутив\\digest.xlsx'
  default:
    font:
      name: Calibry
      size: 10
      bold: False


# Значения по умолчанию, заданные в программе.
# При необходимости можно изменить здесь.
#
#  alignment:
#    horizontal: left
#    vertical: top
#    wrap_text: true
#  columns:
#    - key: task
#      header: "Задача в JIRA"
#      width: 13
#      font:
#         size: 11
#    - key: components
#      header: "Компоненты"
#      width: 30
#    - key: description
#      header: "Описание"
#      width: 30
#      font:
#        size: 11
#    - key: what_changed
#      header: "Что изменено"
#      width: 50
#    - key: how_changed
#      header: "Как изменено"
#      width: 50